export const userURL = "http://localhost:8080/user/api/v1"
export const blogURL = "http://localhost:8080/blog/api/v1"
export const writerURL = "http://localhost:8080/writer/api/v1"
export const otpURL = "http://localhost:8080/otp/api/v1"
export const managerURL = "http://localhost:8080/manager/api/v1"
export const adminURL = "http://localhost:8080/admin/api/v1"
